---

ip: "192.168.10.10"
memory: 4096
cpus: 4
provider: virtualbox
mariadb: true

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:

    - map: ~/.homestead/nginx-configs
      to: /home/vagrant/nginx-configs
      
    - map: ~/workspace
      to: /home/vagrant/workspace
      #type: "nfs"
      #linux__nfs_options: ['async','rw','no_subtree_check','all_squash']
      #options:
      #    mount_options: [ 'nolock', 'vers=3', 'tcp', 'fsc', 'rw', 'noatime' ]
      #    
      # type: "rsync"
      # options:
      #     rsync__args: ["--verbose", "--archive", "--delete", "-zz"]
      #     rsync__exclude: ["node_modules",'.git','tmp']

    

sites:
    
    - map: zh01.dev
      to: /home/vagrant/workspace/y7k/zh01-dearzurich/dist

    - map: zh02.dev
      to: /home/vagrant/workspace/y7k/zh02-dearzurich2017/dist

    - map: zh03.dev
      to: /home/vagrant/workspace/y7k/zh02-dearzurich2017new/public

    - map: vz01.dev
      to: /home/vagrant/workspace/y7k/vz01-tcz/public

    - map: bz02.dev
      to: /home/vagrant/workspace/y7k/bz02-bzlt/public

    - map: hc01.dev
      to: /home/vagrant/workspace/y7k/hc01-hundecodex/public
      
    - map: rh01.dev
      to: /home/vagrant/workspace/y7k/rh01-rosenhof/public
  
    - map: li06.dev
      to: /home/vagrant/workspace/y7k/li06-solari/public

    - map: sp01.dev
      to: /home/vagrant/workspace/y7k/sp01-sp/public
  
    - map: '*.sp01.dev'
      to: /home/vagrant/workspace/y7k/sp01-sp/public

    - map: cg01.dev
      to: /home/vagrant/workspace/y7k/cg01-guye/public

    - map: y708.dev
      to: /home/vagrant/workspace/y7k/y708-y7k/public

    - map: y718.dev
      to: /home/vagrant/workspace/y7k/y718-bday/public
    
    - map: planning.y705.dev
      to: /home/vagrant/workspace/y7k/y705-planning/public
    
    - map: projects.y705.dev
      to: /home/vagrant/workspace/y7k/y705-projects/public
    
    - map: y705.dev
      to: /home/vagrant/workspace/y7k/y705-spark/public
    
    - map: wiki.y705.dev
      to: /home/vagrant/workspace/y7k/y705-wiki/public
    
    - map: web.sr01.dev
      to: /home/vagrant/workspace/y7k/sr01-festivalcontainer-web/public
    
    - map: screen.sr01.dev
      to: /home/vagrant/workspace/y7k/sr01-festivalcontainer-screen/public 

    # - map: mi03.dev
    #   to: /home/vagrant/workspace/y7k/mi03-migrosmuseum/public

    - map: ra01.dev
      to: /home/vagrant/workspace/y7k/ra01-raffinerie/public

    - map: lm01.dev
      to: /home/vagrant/workspace/y7k/lm01-letsmuseum/public

    # - map: cp01.dev
    #   to: /home/vagrant/workspace/y7k/cp01-coop-emoji/public  
    
    # - map: dl07.dev
    #   to: /home/vagrant/workspace/y7k/dl07-sales/public
    
    # - map: dl01.dev
    #   to: /home/vagrant/workspace/y7k/dl01-delaneau/public
        
    # - map: li02.dev
    #   to: /home/vagrant/workspace/y7k/li02-loginvitation/public
    
    # - map: li04.dev
    #   to: /home/vagrant/workspace/y7k/li04-baer/public

    # - map: web.sr06.dev
    #   to: /home/vagrant/workspace/y7k/sr06-fantasy-web/public
    
    # - map: screen.sr06.dev
    #   to: /home/vagrant/workspace/y7k/sr06-fantasy-screen/public
       
    - map: y7k-plate-test.dev
      to: /home/vagrant/workspace/y7k/y7k-plate-test/public
    

databases:
    - as01
    - bz02
    - cg01
    - cp01
    - dl07
    - hc01
    - li02
    - li06
    - lm01
    - mi03 
    - ra01
    - rh01
    - sp01
    - sr01
    - sr06
    - vz01
    - y705-planning
    - y705-projects
    - y705-spark
    - y705-wiki
    - y708
    - y7k-plate-test

# variables:
#     - key: APP_ENV
#       value: local

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

# ports:
#     - send: 93000
#       to: 9300
#     - send: 7777
#       to: 777
#       protocol: udp
